### ISSUE TITLE
Missing key "schemas" under "components"

### ISSUE THREAD

**Issue by robertocommit** [xentral/api-spec-public#1]
# Schema Inaccuracy

```
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Bearer token obtained in POST /tokens endpoint or pregenerated in the system."
      }
    }
  },
```

is missing `schemas` key

## Expected

Presence of `schemas` key

## Reproduction Steps

Visit: https://github.com/instrumenta/openapi2jsonschema

This is an official utility to to extract [JSON Schema](http://json-schema.org/) from a valid [OpenAPI](https://www.openapis.org/) specification.

Once executed, this error is presented:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/openapi2jsonschema", line 8, in <module>
    sys.exit(default())
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openapi2jsonschema/command.py", line 127, in default
    components = data["components"]["schemas"]
                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'schemas'
```

**Comment by avogel91** [comment]
Sorry for the late reply. I don't feel that the `schemas` key is mandatory in the `components` section. Since we are publishing a completely dereferenced OpenAPI JSON schema, having components does not seem to make sense. 

To me it feels that this line in the Python script is not defensive enough (I could be wrong, not a Python expert): https://github.com/instrumenta/openapi2jsonschema/blob/d697cbff8a25f520e125e3a5f79cb4e9b972e8ce/openapi2jsonschema/command.py#L127 and should first check if there is actually a `schemas` key and if not, just make it an empty array. 

If you feel that I am wrong, please reopen.
